# docker-compose up -d 
version: '3.2'

services:
  covid19_app:
    restart: always
    image: linuxserver/letsencrypt::1.6.0-ls134
    volumes:
      # If spawn this container on a specific worker node, this file should already exist on that node 
      - /var/covid19_project/wherecovid19_webapp/deploy/nginx_sitedefault.conf:/config/nginx/site-confs/default
      - /var/covid19_project/wherecovid19_webapp/deploy/nginx_gzip.conf:/config/nginx/nginx.conf
      - /var/covid19_project/wherecovid19_webapp/deploy/mime.types:/etc/nginx/mime.types
      - nginx_volume:/config
      - /var/covid19_project/wherecovid19_webapp:/var/www/covid19_app
    ports:
      - "443:443"
      - "80:80"
    environment:
      - URL=wherecovid19.cigi.illinois.edu
      - EMAIL=zhiyul@illinois.edu

volumes:
  nginx_volume:

